beam: 10
retry_beam: 40

features:
  type: "mfcc"
  use_energy: false
  frame_shift: 10
  pitch: false

training:
  - monophone:
      num_iterations: 40
      max_gaussians: 1000
      subset: 10000

  - triphone:
      num_iterations: 35
      num_leaves: 2500
      max_gaussians: 20000
      cluster_threshold: -1
      subset: 30000
      boost_silence: 1.25
      power: 0.25

  - triphone:
      num_iterations: 35
      num_leaves: 2500
      max_gaussians: 20000
      cluster_threshold: -1
      subset: 30000

  - lda:
      num_leaves: 5000
      max_gaussians: 40000
      left_context: 3
      right_context: 3
      subset: 100000
      num_iterations: 35

  - sat:
      num_leaves: 5000
      max_gaussians: 100000
      fmllr_power: 0.2
      silence_weight: 0.0
      fmllr_update_type: "full"
      subset: 100000

  - sat:
      calc_pron_probs: true
      num_leaves: 10000
      max_gaussians: 300000
      fmllr_power: 0.2
      silence_weight: 0.0
      fmllr_update_type: "full"

