version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

sphinx:
   configuration: docs/source/conf.py

conda:
  environment: environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
