# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = "2.0.0b4.dev13+gf6a4da7.d20211108"
version_tuple = (2, 0, 0, "dev13", "gf6a4da7.d20211108")
