features:
  type: "mfcc"
  use_energy: true
  frame_shift: 10

training:
  - ivector:
      num_iterations: 10
      gaussian_min_count: 2
      silence_weight: 0.0
      posterior_scale: 0.1
      max_count: 100