channels:
  - conda-forge
  - pytorch
  - nvidia
  - anaconda
dependencies:
  - python>=3.11
  - numpy
  - librosa
  - tqdm
  - requests
  - pyyaml
  - kaldi=*=*cpu*
  - pynini
  - openfst
  - scikit-learn
  - hdbscan
  - baumwelch
  - ngram
  - praatio>=6.0.0
  - sqlalchemy>=2.0
  - git
  - cmake
  - make
  - compilers
  - pkg-config
  - pgvector
  - pgvector-python
  - postgresql
  - psycopg2
  - click
  - pytorch<2.9
  - torchaudio<2.9
  - setuptools_scm
  - kneed
  - matplotlib
  - seaborn
  - sqlite
  - rich
  - rich-click
  - kalpy>=0.10
  - spacy
  - sudachipy
  - sudachidict-core
  - spacy-pkuseg
  - sentencepiece
  - huggingface_hub
  - jinja2
  - pip
  - pip:
      - speechbrain==1.0.3
      - jamo
      - pythainlp
      - dragonmapper
